//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextPage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NextPage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new book.
        /// </summary>
        internal static string AddBookPageTitle {
            get {
                return ResourceManager.GetString("AddBookPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this book? This cannot be undone..
        /// </summary>
        internal static string AreYouSureDelete {
            get {
                return ResourceManager.GetString("AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to discard your changes to this book?.
        /// </summary>
        internal static string AreYouSureDiscard {
            get {
                return ResourceManager.GetString("AreYouSureDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with the book you tried to save. Please correct the following error(s):
        ///
        ///{0}.
        /// </summary>
        internal static string BookErrorMessageFormat {
            get {
                return ResourceManager.GetString("BookErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filters &amp; sort.
        /// </summary>
        internal static string ButtonClearFiltersAndSort {
            get {
                return ResourceManager.GetString("ButtonClearFiltersAndSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        internal static string ButtonDiscard {
            get {
                return ResourceManager.GetString("ButtonDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delete.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm discard.
        /// </summary>
        internal static string ConfirmDiscard {
            get {
                return ResourceManager.GetString("ConfirmDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (optional):.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book: {0}.
        /// </summary>
        internal static string EditBookPageTitle {
            get {
                return ResourceManager.GetString("EditBookPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The book must have an Author
        ///.
        /// </summary>
        internal static string EmptyAuthorValidationMessage {
            get {
                return ResourceManager.GetString("EmptyAuthorValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The book must have a Genre
        ///.
        /// </summary>
        internal static string EmptyGenreValidationMessage {
            get {
                return ResourceManager.GetString("EmptyGenreValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The book must have a Title
        ///.
        /// </summary>
        internal static string EmptyTitleValidationMessage {
            get {
                return ResourceManager.GetString("EmptyTitleValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The book must have a Year
        ///.
        /// </summary>
        internal static string EmptyYearValidationMessage {
            get {
                return ResourceManager.GetString("EmptyYearValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre:.
        /// </summary>
        internal static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic.
        /// </summary>
        internal static string GenreAcademic {
            get {
                return ResourceManager.GetString("GenreAcademic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string GenreAction {
            get {
                return ResourceManager.GetString("GenreAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        internal static string GenreAdventure {
            get {
                return ResourceManager.GetString("GenreAdventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        internal static string GenreBiography {
            get {
                return ResourceManager.GetString("GenreBiography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy.
        /// </summary>
        internal static string GenreComedy {
            get {
                return ResourceManager.GetString("GenreComedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking.
        /// </summary>
        internal static string GenreCooking {
            get {
                return ResourceManager.GetString("GenreCooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crime and mystery.
        /// </summary>
        internal static string GenreCrimeAndMystery {
            get {
                return ResourceManager.GetString("GenreCrimeAndMystery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantasy.
        /// </summary>
        internal static string GenreFantasy {
            get {
                return ResourceManager.GetString("GenreFantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horror.
        /// </summary>
        internal static string GenreHorror {
            get {
                return ResourceManager.GetString("GenreHorror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance.
        /// </summary>
        internal static string GenreRomance {
            get {
                return ResourceManager.GetString("GenreRomance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sci-fi.
        /// </summary>
        internal static string GenreSciFi {
            get {
                return ResourceManager.GetString("GenreSciFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-help.
        /// </summary>
        internal static string GenreSelfHelp {
            get {
                return ResourceManager.GetString("GenreSelfHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel.
        /// </summary>
        internal static string GenreTravel {
            get {
                return ResourceManager.GetString("GenreTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True crime.
        /// </summary>
        internal static string GenreTrueCrime {
            get {
                return ResourceManager.GetString("GenreTrueCrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The book must have a valid year e.g. 1999
        ///.
        /// </summary>
        internal static string InvalidYearValidationMessage {
            get {
                return ResourceManager.GetString("InvalidYearValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;A room without books is like a body without a soul.&quot; — Cicero.
        /// </summary>
        internal static string NoBooksMessage {
            get {
                return ResourceManager.GetString("NoBooksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication year:.
        /// </summary>
        internal static string PublicationYear {
            get {
                return ResourceManager.GetString("PublicationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication year: {0}.
        /// </summary>
        internal static string PublicationYearWithParameter {
            get {
                return ResourceManager.GetString("PublicationYearWithParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new book button.
        /// </summary>
        internal static string SemanticDescriptionAddNewBookButton {
            get {
                return ResourceManager.GetString("SemanticDescriptionAddNewBookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current sort type is: {0}, current sort order is: {1}..
        /// </summary>
        internal static string SemanticDescriptionCurrentSortDescription {
            get {
                return ResourceManager.GetString("SemanticDescriptionCurrentSortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete button.
        /// </summary>
        internal static string SemanticDescriptionDeleteButton {
            get {
                return ResourceManager.GetString("SemanticDescriptionDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string SemanticDescriptionLoading {
            get {
                return ResourceManager.GetString("SemanticDescriptionLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Next Page logo with a turning page icon..
        /// </summary>
        internal static string SemanticDescriptionLogo {
            get {
                return ResourceManager.GetString("SemanticDescriptionLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No books were found. &quot;A room without books is like a body without a soul.&quot; — Cicero.
        /// </summary>
        internal static string SemanticDescriptionNoBooksMessage {
            get {
                return ResourceManager.GetString("SemanticDescriptionNoBooksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sort currently selected.
        /// </summary>
        internal static string SemanticDescriptionNoSortSelected {
            get {
                return ResourceManager.GetString("SemanticDescriptionNoSortSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double tap and hold to open book.
        /// </summary>
        internal static string SemanticDescriptionOpenBookInstruction {
            get {
                return ResourceManager.GetString("SemanticDescriptionOpenBookInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search box. Enter your query here..
        /// </summary>
        internal static string SemanticDescriptionSearchPlaceholder {
            get {
                return ResourceManager.GetString("SemanticDescriptionSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort button.
        /// </summary>
        internal static string SemanticDescriptionSortButton {
            get {
                return ResourceManager.GetString("SemanticDescriptionSortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string SortPageTitle {
            get {
                return ResourceManager.GetString("SortPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string SortTypeAuthor {
            get {
                return ResourceManager.GetString("SortTypeAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string SortTypeTitle {
            get {
                return ResourceManager.GetString("SortTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string SortTypeYear {
            get {
                return ResourceManager.GetString("SortTypeYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal book library 📘.
        /// </summary>
        internal static string TagLine {
            get {
                return ResourceManager.GetString("TagLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
