name: Unit Tests

on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ main ]
    
jobs:
  pr:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK ${{env.DOTNETVERSION}}
        uses: actions/setup-dotnet@v2
        with:
          global-json-file: src/global.json

      - name: List installed .NET info
        shell: pwsh
        run: dotnet --info

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore nuget packages
        run: |
          cd src\
          dotnet restore NextPage.sln

      - name: Build and Run UnitTests
        shell: bash
        run: |
          dotnet build tests/NextPage.UnitTests/NextPage.UnitTests.csproj
          dotnet test tests/NextPage.UnitTests/NextPage.UnitTests.csproj --no-build --verbosity normal